name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: build & push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            egeneralov/es-change-passwords:${{ github.sha }}
            egeneralov/es-change-passwords:latest
            docker.pkg.github.com/${{ github.repository }}/es-change-passwords:${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
